### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by Rahul0211** [greyatom-edu-tech/greyatom-ide#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 4.4.10 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.3
**Thrown From**: [greyatom-ide](https://github.com/greyatom-edu-tech/greyatom-ide) package 4.4.10

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/learn-term.js/src/term.js:1599

TypeError: Cannot set property '0' of undefined
    at TerminalWrapper.Terminal.write (/app.asar/node_modules/learn-term.js/src/term.js:1599:55)
    at TerminalWrapper.module.exports.TerminalWrapper.write (/app.asar/node_modules/greyatom-ide/lib/views/terminal-wrapper.js:19:39)
    at /app.asar/node_modules/greyatom-ide/lib/views/terminal.js:127:40)
    at emitOne (events.js:96:13)
    at Terminal.emit (events.js:188:7)
    at /app.asar/node_modules/greyatom-ide/lib/terminal.js:45:26)
    at emitOne (events.js:96:13)
    at PageBus.emit (events.js:188:7)
    at /app.asar/node_modules/page-bus/index.js:21:44
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by PradeepJaiswar** [comment]
This happens when you try to use **nano or vi** in the terminal. This is a knows issue. For writing the code you should code editor.

Closing this as nano or vi editors are not supported in the current terminal for now.
