### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by utk1801** [greyatom-edu-tech/greyatom-ide#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 4.2.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.5
**Thrown From**: [greyatom-ide](https://github.com/greyatom-edu-tech/greyatom-ide) package 4.2.0

### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of undefined

```
At /private/var/folders/qb/gyr3my016zd67p0lb6qz112h0000gn/T/AppTranslocation/BF6D54CD-D6BB-422B-AEAD-209AD8944492/d/Commit Live.app/Contents/Resources/app.asar/node_modules/learn-term.js/src/term.js:1413

TypeError: Cannot set property 'innerHTML' of undefined
    at TerminalWrapper.Terminal.refresh (/app.asar/node_modules/learn-term.js/src/term.js:1413:32)
    at TerminalWrapper.Terminal.write (/app.asar/node_modules/learn-term.js/src/term.js:2557:8)
    at TerminalWrapper.module.exports.TerminalWrapper.write (/app.asar/node_modules/greyatom-ide/lib/views/terminal-wrapper.js:19:39)
    at /app.asar/node_modules/greyatom-ide/lib/views/terminal.js:127:40)
    at emitOne (events.js:96:13)
    at Terminal.emit (events.js:188:7)
    at /app.asar/node_modules/greyatom-ide/lib/terminal.js:45:26)
    at emitOne (events.js:96:13)
    at PageBus.emit (events.js:188:7)
    at /app.asar/node_modules/page-bus/index.js:21:44
```

### Commands

```
  2x -5:04.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by utk1801** [comment]
The terminal pane in Commit Live IDE goes missing after running clive commands and gives the above error..Pls help troubleshoot this.

**Comment by surajhell88** [comment]
Can you let us know the clive command that you executed on the terminal which caused this issue?
