### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type ...

### ISSUE THREAD

**Issue by saahil1292** [greyatom-edu-tech/greyatom-ide#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 4.2.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [greyatom-ide](https://github.com/greyatom-edu-tech/greyatom-ide) package 4.2.0

### Stack Trace

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

```
At /usr/share/atom/resources/app.asar/node_modules/greyatom-ide/lib/views/terminal-wrapper.js:49

TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at TypeError (native)
    at TerminalWrapper.module.exports.TerminalWrapper._proposeGeometry (/app.asar/node_modules/greyatom-ide/lib/views/terminal-wrapper.js:49:35)
    at TerminalWrapper.module.exports.TerminalWrapper.fit (/app.asar/node_modules/greyatom-ide/lib/views/terminal-wrapper.js:38:18)
    at TerminalView.module.exports.TerminalView.fitTerminal (/app.asar/node_modules/greyatom-ide/lib/views/terminal.js:277:37)
    at TerminalView.module.exports.TerminalView.resizeStopped (/app.asar/node_modules/greyatom-ide/lib/views/terminal.js:259:19)
    at /app.asar/node_modules/greyatom-ide/lib/views/terminal.js:3:59)
    at HTMLDocument.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDocument.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -3:26.8.0 greyatom-tree-view:delete-selected (span.name.icon.icon-file-text)
  2x -0:12.7.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
```

### Non-Core Packages

```

```

**Comment by PradeepJaiswar** [comment]
Can you post the step to reproduce this? Screenshot with steps will be helpful.

**Comment by saahil1292** [comment]
I don't even remember how this error came?? But i never encountered this issue again..
You can close the issue if you want..

**Comment by PradeepJaiswar** [comment]
Ok. Closing this.
